export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST";
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS";
export const ADMIN_PRODUCT_FAILURE = "ADMIN_PRODUCT_FAILURE";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";
export const ERROR='ERROR'
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const EDIT_SUCCESS = "EDIT_SUCCESS";
export const REQUEST='REQUEST'
